#!/bin/tcsh -f
echo " This is a TCL file created by sanjana"

set my_work_dir = 'pwd'

if ($#argv != 1) then
        echo "Info : Please provide csv file"
        exit 1
endif

if (! -f $argv[1] || $argv[1] == "-help" )then
        if($argv[1] != "-help" )then
                echo " ERROR: Could not find the file $argv[1]. Exiting... "
                exit 1
        else
                echo "USer manual will be displayed"
                exit 1
        endif
else
        tclsh vsdsynth.tcl $argv[1]
endif

